export const GODBOUND = {
    attributes: {
        str: 'GODBOUND.Attribute.Str.long',
        dex: 'GODBOUND.Attribute.Dex.long',
        con: 'GODBOUND.Attribute.Con.long',
        int: 'GODBOUND.Attribute.Int.long',
        wis: 'GODBOUND.Attribute.Wis.long',
        cha: 'GODBOUND.Attribute.Cha.long',
    },
    attributeAbbreviations: {
        str: 'GODBOUND.Attribute.Str.abbr',
        dex: 'GODBOUND.Attribute.Dex.abbr',
        con: 'GODBOUND.Attribute.Con.abbr',
        int: 'GODBOUND.Attribute.Int.abbr',
        wis: 'GODBOUND.Attribute.Wis.abbr',
        cha: 'GODBOUND.Attribute.Cha.abbr',
    },
    armorTypes: {
        none: 'GODBOUND.Armor.None',
        light: 'GODBOUND.Armor.Light',
        medium: 'GODBOUND.Armor.Medium',
        heavy: 'GODBOUND.Armor.Heavy',
    },
    resources: {
        effort: 'GODBOUND.Resource.Effort',
        health: 'GODBOUND.Resource.Health',
        influence: 'GODBOUND.Resource.Influence',
        dominion: 'GODBOUND.Resource.Dominion',
        wealth: 'GODBOUND.Resource.Wealth',
    },
    weaponTypes: {
        unarmed: 'GODBOUND.Weapon.Unarmed',
        light: 'GODBOUND.Weapon.Light',
        medium: 'GODBOUND.Weapon.Medium',
        heavy: 'GODBOUND.Weapon.Heavy',
        ranged1h: 'GODBOUND.Weapon.OneHandedRanged',
        ranged2h: 'GODBOUND.Weapon.TwoHandedRanged',
    },
    gifts: {
        power: {
            lesser: 'GODBOUND.Item.Gift.Power.Lesser',
            greater: 'GODBOUND.Item.Gift.Power.Greater',
        },
        type: {
            passive: 'GODBOUND.Item.Gift.Type.Passive',
            instant: 'GODBOUND.Item.Gift.Type.Instant',
            turn: 'GODBOUND.Item.Gift.Type.Turn',
            action: 'GODBOUND.Item.Gift.Type.Action',
        },
    },
    words: {
        alacrity: 'GODBOUND.Item.Word.Alacrity',
        apotheosis: 'GODBOUND.Item.Word.Apotheosis',
        artifice: 'GODBOUND.Item.Word.Artifice',
        beasts: 'GODBOUND.Item.Word.Beast',
        birds: 'GODBOUND.Item.Word.Birds',
        bow: 'GODBOUND.Item.Word.Bow',
        cities: 'GODBOUND.Item.Word.Cities',
        command: 'GODBOUND.Item.Word.Command',
        dance: 'GODBOUND.Item.Word.Dance',
        deception: 'GODBOUND.Item.Word.Deception',
        desire: 'GODBOUND.Item.Word.Desire',
        endurance: 'GODBOUND.Item.Word.Endurance',
        engineering: 'GODBOUND.Item.Word.Engineering',
        entropy: 'GODBOUND.Item.Word.Entropy',
        fate: 'GODBOUND.Item.Word.Fate',
        fear: 'GODBOUND.Item.Word.Fear',
        fertility: 'GODBOUND.Item.Word.Fertility',
        fire: 'GODBOUND.Item.Word.Fire',
        health: 'GODBOUND.Item.Word.Health',
        insects: 'GODBOUND.Item.Word.Insects',
        intoxication: 'GODBOUND.Item.Word.Intoxication',
        journeying: 'GODBOUND.Item.Word.Journeying',
        knowledge: 'GODBOUND.Item.Word.Knowledge',
        luck: 'GODBOUND.Item.Word.Luck',
        madness: 'GODBOUND.Item.Word.Madness',
        might: 'GODBOUND.Item.Word.Might',
        murder: 'GODBOUND.Item.Word.Murder',
        music: 'GODBOUND.Item.Word.Music',
        network: 'GODBOUND.Item.Word.Network',
        night: 'GODBOUND.Item.Word.Night',
        passion: 'GODBOUND.Item.Word.Passion',
        protection: 'GODBOUND.Item.Word.Protection',
        sea: 'GODBOUND.Item.Word.Sea',
        shapeshifting: 'GODBOUND.Item.Word.Shapeshifting',
        sky: 'GODBOUND.Item.Word.Sky',
        sorcery: 'GODBOUND.Item.Word.Sorcery',
        sun: 'GODBOUND.Item.Word.Sun',
        sword: 'GODBOUND.Item.Word.Sword',
        theft: 'GODBOUND.Item.Word.Theft',
        time: 'GODBOUND.Item.Word.Time',
        underworld: 'GODBOUND.Item.Word.Underworld',
        vengeance: 'GODBOUND.Item.Word.Vengeance',
        war: 'GODBOUND.Item.Word.War',
        wealth: 'GODBOUND.Item.Word.Wealth',
        winter: 'GODBOUND.Item.Word.Winter',
    },
}





